### PR TITLE
Refactor settings screens

### PR DESCRIPTION
**Pull request by jlsilva1994**
This MR adds the settings menu screen and the 3 sub-screens schedules, locations and context apps.
Some alterations wore made in the Onboarding classes to be able to extend them on the settings classes.

### CODE REVIEW

**Comment by FranciscoRibeiro** [comment]
I tried removing the Google Maps app from the Commute context and it didn't work. It stayed in the home screen, although it was removed from the contexts menu. Restarting Kairos made the app in question show up again in the contexts menu.

I guess this menu is not working properly. I can try and take a look at the code later

**Comment by hgg** [comment]
@FranciscoRibeiro what you mention is fixed in #58 :wink:

**Review by hgg — CHANGES_REQUESTED** [review]
Overall great work :+1: It's good to leverage the screens from the onboarding, although I think in the future we could come up with a more compact version for the settings.

I'd just like to request that you make the color of the text and icons on the settings main screen to the same color as on the onboarding (that grey-ish color) and add a brief description for each icon.
Something like:
image

Also, make the secondary screens from the settings come from the right to the left. It makes more visual sense.

Finally, delete the layout `context_related_settings.xml` and rename the layout `kairos_settings.xml` to `settings_activity.xml`

**Review by hgg — APPROVED** [review]

**Review by FranciscoRibeiro — APPROVED** [review]
Tested and looks like it's working :)
Go ahead or in other words "chucha-lhe"

**Pull request merged**
