### PR TITLE
Onboarding espresso test

### PR DESCRIPTION
**Pull request by BrunoJAzevedo**
OnBoarding Espresso Automatic test

**Unistall Adamastor 
Run the test, the first time it will fail because it has to be given permissions to the app (Espresso doesn't deal with multiple apps)
Run again and it should pass**
OnBoarding only appears on the first time starting the app, that's why it has to be uninstall to test OnBoarding

**It also is added to gradle Roboletric and Mockito to the creation of unit testing**

### CODE REVIEW

**Review by hgg — COMMENTED** [review]
I followed your instructions and couldn't get the test to pass. I tested with an emulator, should I be using an actual device?

**Comment by hgg** [comment]
@BrunoJAzevedo any news?

**Comment by BrunoJAzevedo** [comment]
There's a problem with the apps in each context, your emulator should have the apps that are chosen installed and visible without scrolling. The apps are: Calculator, Calendar, Camera visible 
Is there were the test is crashing? Or in another point of the test?

**Comment by djcouto** [comment]
Throws this error and fails the test.
```JAVA
01-30 16:15:20.361 28079-28092/? I/TestRunner: failed: onBoardingEspressoTest(corp.kairos.adamastor.Home.OnBoardingEspressoTest)
01-30 16:15:20.361 28079-28092/? I/TestRunner: ----- begin exception -----
01-30 16:15:20.363 28079-28092/? I/TestRunner: android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: corp.kairos.adamastor:id/start and with text: is "Start" and Child at position 0 in parent Child at position 3 in parent with class name: is "android.widget.LinearLayout" and is displayed on the screen to the user)
                                               If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:android.widget.ListView{cf910c9 VFED.VC.. .F...... 0,0-1080,1428 #7f080049 app:id/check_apps_list}
                                               
                                               View Hierarchy:
                                               +>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) ty=1 fl=#81810500 wanim=0x103045b needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
                                               |
                                               +->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1776, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@cd0bf0b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
                                               |
                                               +-->ViewStub{id=16909227, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c98e1e8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
                                               |
                                               +-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1776, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b464ea6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
                                               |
                                               +--->ActionBarOverlayLayout{id=2131230822, res-name=decor_content_parent, visibility=VISIBLE, width=1080, height=1776, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@889ab3d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
                                               |
                                               +---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1608, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.v7.widget.ActionBarOverlayLayout$LayoutParams@bf00483, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=168.0, child-count=1} 
                                               |
                                               +----->ConstraintLayout{id=-1, visibility=VISIBLE, width=1080, height=1608, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ceabe39, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
                                               |
                                               +------>LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1608, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@e83822c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
                                               |
                                               +--
01-30 16:15:20.363 28079-28092/? I/TestRunner: ----- end exception -----
01-30 16:15:20.366 28079-28092/? I/TestRunner: finished: onBoardingEspressoTest(corp.kairos.adamastor.Home.OnBoardingEspressoTest)
01-30 16:15:20.368 28079-28079/? I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 1
01-30 16:15:20.368 28079-28079/? I/MonitoringInstr: Finishing activity: corp.kairos.adamastor.Onboarding.Onboard4ContextAppsActivity@ee4d851
01-30 16:15:20.385 28079-28092/? I/MonitoringInstr: Unstopped activity count: 1
01-30 16:15:20.385 28079-28079/? D/LifecycleMonitor: Lifecycle status change: corp.kairos.adamastor.Onboarding.Onboard4ContextAppsActivity@ee4d851 in: PAUSED
01-30 16:15:20.418 28079-28079/? D/LifecycleMonitor: Lifecycle status change: corp.kairos.adamastor.Onboarding.Onboard4ContextAppsActivity@ee4d851 in: STOPPED
01-30 16:15:20.419 28079-28079/? D/LifecycleMonitor: Lifecycle status change: corp.kairos.adamastor.Onboarding.Onboard4ContextAppsActivity@ee4d851 in: DESTROYED
01-30 16:15:20.420 1631-1631/? D/FeedController: feed controller resume
01-30 16:15:20.436 28079-28092/? I/TestRunner: run finished: 1 tests, 1 failed, 0 ignored
01-30 16:15:20.446 28079-28092/? W/InfraTrack: Analytics post: Espresso=3.0.0 failed. 
01-30 16:15:20.447 28079-28092/? W/InfraTrack: Analytics post: AndroidJUnitRunner=1.0.0 failed. 
01-30 16:15:20.447 28079-28092/? I/MonitoringInstr: waitForActivitiesToComplete() took: 0ms
01-30 16:15:20.448 777-959/? I/ActivityManager: Force stopping corp.kairos.adamastor appid=10169 user=0: finished inst
01-30 16:15:20.448 777-959/? I/ActivityManager: Killing 28079:corp.kairos.adamastor/u0a169 (adj 0): stop corp.kairos.adamastor
01-30 16:15:20.454 777-790/? W/ActivityManager: Error shutting down UiAutomationConnection
01-30 16:15:20.464 1479-1479/? W/Binder_6: type=1400 audit(0.0:659): avc: denied { ioctl } for path="socket:[89649]" dev="sockfs" ino=89649 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-30 16:15:20.464 1479-1479/? W/Binder_6: type=1400 audit(0.0:660): avc: denied { ioctl } for path="socket:[89649]" dev="sockfs" ino=89649 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-30 16:15:20.475 1558-1558/? I/GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
01-30 16:15:20.475 1558-1558/? I/GoogleInputMethod: onStartInput() : Dummy InputConnection bound
01-30 16:15:20.489 777-1647/? I/WindowState: WIN DEATH: Window{78210b5 u0 corp.kairos.adamastor/corp.kairos.adamastor.Onboarding.Onboard4ContextAppsActivity}
01-30 16:15:20.489 777-1649/? D/GraphicsStats: Buffer count: 7
01-30 16:15:20.541 777-959/? D/ActivityManager: cleanUpApplicationRecord -- 28079
01-30 16:15:20.544 777-1815/? W/ActivityManager: Spurious death for ProcessRecord{e62ba53 0:corp.kairos.adamastor/u0a169}, curProc for 28079: null
01-30 16:15:20.597 1631-28496/? I/AppsFlyer_6.0: caching request...
01-30 16:15:20.944 777-798/? W/WindowAnimator: Failed to dispatch window animation state change.
                                               android.os.DeadObjectException
                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                   at android.os.BinderProxy.transact(Binder.java:503)
                                                   at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                   at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                   at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                   at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                   at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                   at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                   at android.os.Looper.loop(Looper.java:148)
                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                   at com.android.server.ServiceThread.run(ServiceThread.java:46)
01-30 16:15:21.018 1631-2110/? W/OpenGLRenderer: Incorrectly called buildLayer on View: be, destroying layer...
01-30 16:15:21.018 1631-2110/? W/OpenGLRenderer: Incorrectly called buildLayer on View: be, destroying layer...
01-30 16:15:22.218 198-813/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
01-30 16:15:22.218 198-813/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
01-30 16:15:48.971 777-800/? I/PowerManagerService: Going to sleep due to screen timeout (uid 1000)...
01-30 16:15:48.971 777-800/? I/PowerManagerService: Sleeping (uid 1000)...
01-30 16:15:49.047 1558-1558/? I/GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
01-30 16:15:49.047 1558-1558/? I/GoogleInputMethod: onStartInput() : Dummy InputConnection bound
01-30 16:15:48.964 1778-1778/? W/Binder_B: type=1400 audit(0.0:661): avc: denied { ioctl } for path="socket:[89649]" dev="sockfs" ino=89649 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-30 16:15:48.964 1778-1778/? W/Binder_B: type=1400 audit(0.0:662): avc: denied { ioctl } for path="socket:[89649]" dev="sockfs" ino=89649 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-30 16:15:49.478 1631-1631/? D/FeedController: feed controller pause
01-30 16:15:49.503 777-800/? V/KeyguardServiceDelegate: onScreenTurnedOff()
01-30 16:15:49.544 777-798/? I/DisplayManagerService: Display device changed state: "Ecrã Integrado", OFF
01-30 16:15:49.551 191-191/? D/SurfaceFlinger: Set power mode=0, type=0 flinger=0xb6ae4000
01-30 16:15:49.551 191-191/? D/qdhwcomposer: hwc_blank: Blanking display: 0
01-30 16:15:49.821 191-191/? D/qdhwcomposer: hwc_blank: Done blanking display: 0
01-30 16:15:49.821 777-906/? D/SurfaceControl: Excessive delay in setPowerMode(): 277ms
01-30 16:15:49.822 2259-2262/? E/ANDR-PERF-LOCK: Failed to apply optimization for resource: 4 level: 0
01-30 16:15:49.873 198-1081/? D/audio_hw_primary: adev_set_parameters: enter: screen_state=off
01-30 16:15:49.894 777-888/? D/WifiConfigStore: Retrieve network priorities after PNO.
01-30 16:15:49.912 777-888/? E/native: do suspend true
01-30 16:15:49.920 1558-1558/? I/GoogleInputMethod: onReceive() : Action = android.intent.action.SCREEN_OFF
```

**Pull request closed without merging**
