### PR TITLE
Select context apps view

### PR DESCRIPTION
**Pull request by jlsilva1994**
changes in this MR:
 - created activity to select the context apps for each context.
 - tabLayout using PageViewer and fragments
 - add button to context apps screen to open this activity, and change onResume to refresh the sections for each context
 - changes in styles and colors

### CODE REVIEW

**Comment by djcouto** [comment]
The result it's good, but you should really ask @joaofcosta him what he thinks, as It is a little different from his mockup. In my opinion it's a beautiful screen, but I'm afraid that the style don't fit with the rest of the launcher style. But I don't know, it's just a concern, don't take it personally really.

Also I noticed a few problems:
* As you can see in the image the confirm appears behind the 3 buttons.  I'm sure you will easily fix this.
* You made an crossfade transition when the screen goes out but a normally transition when it comes in. They should be the same.

As I said, great work, really like you autonomy but ask @joaofcosta  about it :+1: 


screenshot_20180130-162915

**Comment by djcouto** [comment]
@jlsilva1994 updates on this? I think that you already solve this but forgot to push them, right? :wink:

**Comment by jlsilva1994** [comment]
changes implemented, now the design looks like it should be

**Review by djcouto — APPROVED** [review]
@jlsilva1994 good work seems nice to me, ready be merged :+1:

**Pull request merged**
